"""M5 — live rechtspraak.nl audit for HR coverage gap (AQ3).

Purpose:
1. Query rechtspraak.nl for HR decisions with verbintenissenrecht subject,
   modified >= 2024-07-01.
2. Fetch each, apply the M5-expanded huur fence, collect signal-passing ECLIs.
3. Diff against current cases.lance HR ECLI set.
4. Verify whether ECLI:NL:HR:2024:1780 exists on rechtspraak.nl at all.
5. Write findings to docs/evaluations/2026-04-22-m5-hr-audit.md.
6. Write the priority list to data/priority_eclis/huurrecht.txt.

Run: ANTHROPIC_API_KEY not needed. Only rechtspraak.nl is touched.

Usage:  uv run python scripts/audit_hr_coverage.py
"""
from __future__ import annotations

import logging
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

from jurist.config import settings
from jurist.ingest.caselaw_fetch import fetch_content, list_eclis
from jurist.ingest.caselaw_filter import passes as filter_passes
from jurist.ingest.caselaw_parser import ParseError, parse_case
from jurist.ingest.caselaw_profiles import PROFILES
from jurist.vectorstore import CaseStore

REPORT_PATH = Path("docs/evaluations/2026-04-22-m5-hr-audit.md")
PRIORITY_LIST_PATH = Path("data/priority_eclis/huurrecht.txt")
TARGET_ECLI_FROM_REVIEWER = "ECLI:NL:HR:2024:1780"

# list_eclis yields (ecli, updated_ts) tuples; subject_uri is the full URI.
_HR_SUBJECT_URI = PROFILES["huurrecht"].subject_uri


def fetch_candidate_hr_eclis() -> list[str]:
    """Query rechtspraak.nl for verbintenissenrecht decisions >= 2024-07-01, HR only."""
    all_eclis = list(list_eclis(
        subject_uri=_HR_SUBJECT_URI,
        since="2024-07-01",
        max_list=10_000,
    ))
    # list_eclis yields (ecli, updated_ts) tuples
    return [ecli for ecli, _ts in all_eclis if ecli.startswith("ECLI:NL:HR:")]


def verify_ecli_exists(ecli: str) -> bool:
    """HEAD check against data.rechtspraak.nl/uitspraken/content?id=<ecli>."""
    url = f"https://data.rechtspraak.nl/uitspraken/content?id={urllib.parse.quote(ecli, safe=':')}"
    try:
        req = urllib.request.Request(url, method="HEAD")
        with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
            return resp.status == 200
    except urllib.error.HTTPError as e:
        return e.code != 404
    except Exception:
        return False


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    log = logging.getLogger("audit_hr_coverage")

    # 1. Existing HR ECLIs in index — use the public all_eclis() helper
    store = CaseStore(settings.lance_path)
    store.open_or_create()
    all_in_index = store.all_eclis()
    existing = {e for e in all_in_index if e.startswith("ECLI:NL:HR:")}
    log.info(
        "existing HR ECLIs in index: %d (total in index: %d)",
        len(existing),
        len(all_in_index),
    )

    # 2. Candidate HR ECLIs from live rechtspraak.nl
    candidates = fetch_candidate_hr_eclis()
    log.info("candidate HR ECLIs from live listing: %d", len(candidates))

    # 3. Fence-filter candidates by fetching + applying M5-expanded huur fence
    profile = PROFILES["huurrecht"]
    cache_dir = settings.cases_dir
    cache_dir.mkdir(parents=True, exist_ok=True)

    to_add: list[str] = []
    for ecli in candidates:
        if ecli in existing:
            continue
        try:
            xml_path = fetch_content(ecli, cache_dir=cache_dir)
            meta = parse_case(xml_path.read_bytes())
        except (ParseError, Exception) as exc:
            log.warning("fetch/parse failed for %s: %s", ecli, exc)
            continue
        if filter_passes(meta.body_text, terms=profile.keyword_terms):
            to_add.append(ecli)
    log.info("candidates passing M5 fence: %d", len(to_add))

    # 4. Verify the reviewer's claimed ECLI
    target_exists = verify_ecli_exists(TARGET_ECLI_FROM_REVIEWER)
    log.info(
        "reviewer-claimed ECLI %s exists on rechtspraak.nl: %s",
        TARGET_ECLI_FROM_REVIEWER,
        target_exists,
    )
    if (
        target_exists
        and TARGET_ECLI_FROM_REVIEWER not in existing
        and TARGET_ECLI_FROM_REVIEWER not in to_add
    ):
        to_add.append(TARGET_ECLI_FROM_REVIEWER)

    # 5. Write priority list
    PRIORITY_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
    PRIORITY_LIST_PATH.write_text(
        "# M5 curated huur-HR priority list — generated by scripts/audit_hr_coverage.py\n"
        f"# Generated at: {datetime.now(UTC).isoformat()}\n"
        + "\n".join(to_add)
        + ("\n" if to_add else ""),
        encoding="utf-8",
    )

    # 6. Write audit report
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# M5 HR coverage audit — 2026-04-22",
        "",
        f"**Existing HR ECLIs in `cases.lance`:** {len(existing)}",
        (
            f"**Candidate HR ECLIs from live rechtspraak.nl"
            f" (>= 2024-07-01, verbintenissenrecht):** {len(candidates)}"
        ),
        f"**Candidates passing M5-expanded huur fence:** {len(to_add)}",
        "",
        (
            f"**Reviewer-claimed ECLI `{TARGET_ECLI_FROM_REVIEWER}`"
            f" exists on rechtspraak.nl:** {target_exists}"
        ),
        "",
        "## New ECLIs on priority list",
        *(
            [f"- {e}" for e in to_add]
            if to_add
            else ["_(none — all already indexed or no fence-passing candidates)_"]
        ),
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {PRIORITY_LIST_PATH} ({len(to_add)} ECLIs)")
    print(f"wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
